version: '3.3'

services:

  picontrolpanel:
    image: raspberry/picontrolpanel:prod
    container_name: raspberry_picontrolpanel
    build:
      context: ../.
      dockerfile: Docker/Dockerfile.pi
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - '8081:80'
